---
title: "Drizzy Analysis"
output: html_document
date: "2024-12-06"
---

```{r}
library(tidyverse)
```

```{r}
drizzy_df <- read_csv("~/BSAFall2024/DiddyProject/Drizzy-Stats/drizzygames.csv")
```

```{r}
team_colors <- c(
  "MIA" = "#98002e",
  "BOS" = "#007a33",
  "NJN" = "#c6cfd4",
  "BRK" = "black",
  "CHI" = "#ce1141",
  "PHO" = "#e56020",
  "DEN" = "#0e2240",
  "GSW" = "#1d428a",
  "IND" = "#002d62",
  "MIL" = "#00471b",
  "NOP" = "#85714d",
  "NOH" = "#17bfdd",
  "OKC" = "#007ac1",
  "PHI" = "#006bb6",
  "SAC" = "#5a2d81",
  "TOR" = "#ba0c2f",
  "CLE" = "#860038",
  "LAL" = "#552583",
  "LAC" = "#c8102e",
  "CHO" = "#00788c",
  "ATL" = "#e03a3e",
  "DAL" = "#00538c",
  "DET" = "#1d42ba",
  "HOU" = "#ffc72c",
  "MEM" = "#5d76a9",
  "MIN" = "#78be20",
  "NYK" = "#f58426",
  "ORL" = "#0077c0",
  "POR" = "#e03a3e",
  "SAS" = "#8a8d8f",
  "UTA" = "#f9a01b",
  "WAS" = "#002b5c"
)
```

```{r}
drizzy_df <- drizzy_df |> 
  filter(!(mp %in% c("Did Not Dress", "Not With Team", 
                                             "Player Suspended"))) |>
  select(-`...1`)

drizzy_df |> head()
```

# Game Plot

```{r}
drizzy_df$date |> unique() |> sort()
```


```{r}
game_count_df <- drizzy_df |>
  group_by(date, team) |>
  slice(1) |>
  ungroup()
```

```{r}
game_count_df$team |> table()
```
```{r}
unique(game_count_df$team) |> sort()
```

Drake has never been to a Jazz or Nuggets game

```{r}
ggplot(game_count_df, aes(x = fct_infreq(team), fill = team)) + 
  geom_bar() + 
  scale_fill_manual(values = team_colors) + 
  labs(title="Drake's Favorite Teams to Watch", x="Teams", y="Number of Games with Diddy in Attendance") +
  guides(fill="none") +
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

# Player plot
```{r}
player_count_df <- drizzy_df |> 
  count(player, sort = TRUE) |>
  slice_head(n = 20)

player_count_df$player

top_20_players <- drizzy_df |>
  filter(player %in% player_count_df$player) |> 
  arrange(player)
```

```{r}
ggplot(top_20_players, aes(x = fct_infreq(player), fill = team)) +
  geom_bar() + 
  scale_fill_manual(values = team_colors) + 
  labs(title="The Top 20 Players with the Most Drizzy Games",x="Player", y="Number of Games with Diddy in Attendance") +
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
player_count_df

```
```{r}
drizzy_df |> filter(player == "Shaun Livingston")
```

```{r}
drizzy_df |> filter(player == "Pau Gasol")
```
```{r}
drizzy_df |> 
  filter(player == "LeBron James") |> 
  summarise(across(where(is.double), function(x) mean(x)))
```

```{r}
lebron_df <- drizzy_df |>
  filter(player == "LeBron James")
```

```{r}
lebron_df <- lebron_df |> 
  mutate(season = case_when(
    date >= as.Date("1996-10-01") & date <= as.Date("1997-07-31") ~ "1996-97",
    date >= as.Date("1997-10-01") & date <= as.Date("1998-07-31") ~ "1997-98",
    date >= as.Date("1998-10-01") & date <= as.Date("1999-07-31") ~ "1998-99",
    date >= as.Date("1999-10-01") & date <= as.Date("2000-10-11") ~ "1999-00",
    date >= as.Date("2000-10-01") & date <= as.Date("2001-07-31") ~ "2000-01",
    date >= as.Date("2001-12-01") & date <= as.Date("2002-07-31") ~ "2001-02",
    date >= as.Date("2002-10-01") & date <= as.Date("2003-07-31") ~ "2002-03",
    date >= as.Date("2003-10-01") & date <= as.Date("2004-07-31") ~ "2003-04",
    date >= as.Date("2004-10-01") & date <= as.Date("2005-07-31") ~ "2004-05",
    date >= as.Date("2005-10-01") & date <= as.Date("2006-07-31") ~ "2005-06",
    date >= as.Date("2006-10-01") & date <= as.Date("2007-07-31") ~ "2006-07",
    date >= as.Date("2007-10-01") & date <= as.Date("2008-07-31") ~ "2007-08",
    date >= as.Date("2008-10-01") & date <= as.Date("2009-07-31") ~ "2008-09",
    date >= as.Date("2009-10-01") & date <= as.Date("2010-10-11") ~ "2009-10",
    date >= as.Date("2010-10-01") & date <= as.Date("2011-07-31") ~ "2010-11",
    date >= as.Date("2011-12-01") & date <= as.Date("2012-07-31") ~ "2011-12",
    date >= as.Date("2012-10-01") & date <= as.Date("2013-07-31") ~ "2012-13",
    date >= as.Date("2013-10-01") & date <= as.Date("2014-07-31") ~ "2013-14",
    date >= as.Date("2014-10-01") & date <= as.Date("2015-07-31") ~ "2014-15",
    date >= as.Date("2015-10-01") & date <= as.Date("2016-07-31") ~ "2015-16",
    date >= as.Date("2016-10-01") & date <= as.Date("2017-07-31") ~ "2016-17",
    date >= as.Date("2017-10-01") & date <= as.Date("2018-07-31") ~ "2017-18",
    date >= as.Date("2018-10-01") & date <= as.Date("2019-07-31") ~ "2018-19",
    date >= as.Date("2019-10-01") & date <= as.Date("2020-10-11") ~ "2019-20",
    date >= as.Date("2020-12-01") & date <= as.Date("2021-07-31") ~ "2020-21",
    date >= as.Date("2021-10-01") & date <= as.Date("2022-07-31") ~ "2021-22",
    date >= as.Date("2022-10-01") & date <= as.Date("2023-07-31") ~ "2022-23",
    date >= as.Date("2023-10-01") & date <= as.Date("2024-07-31") ~ "2023-24",
    TRUE ~ "Other"
  ))
```

```{r}
playoff_dates <- as.Date(c("2009-04-27", "2023-04-24", "2013-04-23"))

lebron_df <- lebron_df |>
  mutate(game_type = if_else(
    month(date) %in% c(5, 6)| date %in% playoff_dates,
    "playoff",
    "regular"
  ))
```

```{r}
career_stats_df <- read_csv("~/BSAFall2024/DiddyProject/Diddy-Stats/top20.csv")

career_stats_df <- career_stats_df |> 
  select(-c(pos, lg_id, team_id, gs, `...1`, age, DUMMY, trp_dbl))

career_stats_pg_df <- career_stats_df |>
  mutate(across(c(mp, fg, fga, fg3, fg3a, fg2, fg2a, ft, fta, orb, drb, trb, ast, stl,
                  blk, tov, pf, pts), function(x) round(x / g, digits = 2)))
```
```{r}
combined_plots <- function(combined_df, stat) { 
  player_name <- combined_df$player[1]
  select_cols <- c("player", "season", "season_type", "date", stat, paste0("career_", stat))
  
  combined_df <- combined_df |>
    select(all_of(select_cols))
  
  combined_df_long <- combined_df |> 
    pivot_longer(cols = all_of(c(stat, paste0("career_", stat))),
               names_to = "stat_type",
               values_to = "value") |>
    mutate(stat_type = case_when(
      stat_type == paste0("career_", stat) ~ paste("Season", stat),
      stat_type == stat ~ paste("Diddy", stat)
    ))
  
  combined_df_long <- combined_df |> 
    pivot_longer(cols = all_of(c(stat, paste0("career_", stat))),
                 names_to = "stat_type",
                 values_to = "value") |>
    mutate(stat_type = case_when(
      stat_type == paste0("career_", stat) ~ paste("Season", stat),
      stat_type == stat ~ paste("Drake", stat)
    ))
  
  fill_labels <- setNames(c("red", "green"), 
                          c(paste0("Drake ", stat), paste0("Season ", stat)))
  
  ggplot(combined_df_long, 
         aes(x = factor(date), y = value, fill = stat_type)) +
    geom_bar(stat = "identity", position = position_dodge()) +
    scale_fill_manual(values = fill_labels) +
    facet_wrap(~season_type, nrow = 2) +
    labs(x = "Date of Game", y = stat, title=paste0("Drake's effect on ", player_name, "'s ", stat), fill = "Stat Type") + 
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
}
```

```{r}
lebron_combined <- combine_career_diddy(lebron_df, career_stats_pg_df, "Lebron James") 
```
```{r}

combined_plots(lebron_combined, "pts")
combined_plots(lebron_combined, "ast")
combined_plots(lebron_combined, "trb")
combined_plots(lebron_combined, "stl")
combined_plots(lebron_combined, "blk")
combined_plots(lebron_combined, "pf")
```

```{r}
lebron_df |> arrange(game_score)
```

```{r}
stat_differential <- function(combined_df) {
  # c(pts, pf, tov, blk, stl, ast, trb)
  
  diff_df <- combined_df |> 
    mutate(diff_pts = pts - career_pts,
           diff_pf = pf - career_pf,
           diff_tov = tov - career_tov,
           diff_blk = blk - career_blk,
           diff_stl = stl - career_stl, 
           diff_ast = ast - career_ast,
           diff_trb = trb - career_trb,
             ) |> 
    select(
          player, season, season_type, diff_pts, diff_ast, diff_trb, diff_tov, diff_blk, diff_stl, diff_pf
      )
  
  return(diff_df)
}
```

```{r}
lebron_diff <- stat_differential(lebron_combined)

lebron_diff
```
```{r}
lebron_diff |> arrange(season_type)
```


```{r}
lebron_diff |> group_by(season_type) |> summarise(across(where(is.double), function(x) mean(x)))

lebron_diff |> summarise(across(where(is.double), function(x) mean(x)))

```

# Significance Test
Using Hotelling's one sample T2-test
```{r}
# install.packages("ICSNP")
library("ICSNP")
```

```{r}
# Preparing data for testing
lebron_diff_test <- lebron_diff |> 
  select(diff_pts, diff_ast, diff_trb, diff_tov, diff_tov, diff_blk, diff_stl, diff_pf)

lebron_diff_test
```

```{r}
# Comparing lebron's games to the average 
HotellingsT2(lebron_diff_test, mu = rep(0, ncol(lebron_diff_test)))
```
```{r}
# From diddyviz.Rmd, run to get into workspace
goat_diff_test <- goat_diff |>
  select(diff_pts, diff_ast, diff_trb, diff_tov, diff_tov, diff_blk, diff_stl, diff_pf)

goat_diff_test
```
```{r}
# Not enough data :(
HotellingsT2(goat_diff_test, mu = rep(0, ncol(goat_diff_test)))
```
```{r}
goat_diff_test
```


```{r}
HotellingsT2(lebron_diff_test, goat_diff_test)
```

